# Generated by Django 3.0.14 on 2022-10-29 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(default='', help_text='Please enter the ID of the related object.', max_length=255, verbose_name='Related object')),
                ('owner_object_id', models.CharField(default='', help_text='Please enter the ID of the related object.', max_length=255, verbose_name='Owner')),
                ('content_type', models.ForeignKey(help_text='Please select the type (model) for the relation, you want to build.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name="Related object's type (model)")),
                ('owner_content_type', models.ForeignKey(help_text='Please select the type (model) for the relation, you want to build.', limit_choices_to={'model': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='contenttypes.ContentType', verbose_name="Owner's type (model)")),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='IdeaWithTranslatedFields',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('raiting', models.PositiveSmallIntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True, verbose_name='Raiting')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('categories', models.ManyToManyField(blank=True, related_name='ideas', to='categories.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Idea With Translations',
                'verbose_name_plural': 'Ideas With Translations',
            },
        ),
        migrations.CreateModel(
            name='IdeaTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=7, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='ideas.IdeaWithTranslatedFields', verbose_name='Idea')),
            ],
            options={
                'verbose_name': 'Idea Translations',
                'verbose_name_plural': 'Idea Translations',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modefied', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('meta_keywords', models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('meta_author', models.CharField(blank=True, max_length=255, verbose_name='Author')),
                ('meta_copyright', models.CharField(blank=True, max_length=255, verbose_name='Copyright')),
                ('title_en', models.CharField(db_tablespace='', max_length=200, verbose_name='Title (English)')),
                ('title_ru', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Russian)')),
                ('title_fr', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (French)')),
                ('title_de', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (German)')),
                ('content_en', models.TextField(db_tablespace='', verbose_name='Content (English)')),
                ('content_ru', models.TextField(blank=True, db_tablespace='', verbose_name='Content (Russian)')),
                ('content_fr', models.TextField(blank=True, db_tablespace='', verbose_name='Content (French)')),
                ('content_de', models.TextField(blank=True, db_tablespace='', verbose_name='Content (German)')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='categories.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(default='', help_text='Please enter the ID of the related object.', max_length=255, verbose_name='Related object')),
                ('commentator_object_id', models.CharField(default='', help_text='Please enter the ID of the related object.', max_length=255, verbose_name='Commentator')),
                ('text', models.CharField(help_text='Enter your comment', max_length=255, null=True, verbose_name='Comment text')),
                ('commentator_content_type', models.ForeignKey(help_text='Please select the type (model) for the relation, you want to build.', limit_choices_to={'model': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to='contenttypes.ContentType', verbose_name="Commentator's type (model)")),
                ('content_type', models.ForeignKey(help_text='Please select the type (model) for the relation, you want to build.', limit_choices_to={'model__in': ('idea', 'newsarticle')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name="Related object's type (model)")),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddConstraint(
            model_name='ideawithtranslatedfields',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, author=None), fields=('title',), name='unique_title_for_each_author'),
        ),
        migrations.AddConstraint(
            model_name='ideawithtranslatedfields',
            constraint=models.CheckConstraint(check=models.Q(title__iregex='^\\S.*\\S$'), name='title_has_no_leading_and_traling_whitespaces'),
        ),
        migrations.AlterUniqueTogether(
            name='ideatranslations',
            unique_together={('idea', 'language')},
        ),
    ]
