# Generated by Django 3.0.14 on 2022-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideawithtranslatedfields',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='categories.Category', verbose_name='Categories'),
        ),
    ]
