# Generated by Django 3.0.14 on 2022-10-27 14:30

from django.db import migrations


def copy_categories(apps, schema_editor):
    Idea = apps.get_model('ideas', 'IdeaWithTranslatedFields')
    for idea in Idea.objects.all():
        if idea.category:
            idea.categories.add(idea.category)


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_ideawithtranslatedfields_categories'),
    ]

    operations = [
        migrations.RunPython(copy_categories)
    ]
