# Generated by Django 3.0.14 on 2022-11-18 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20221110_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideawithtranslatedfields',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideawithtranslatedfields',
            name='modefied',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time'),
        ),
    ]
