# Generated by Django 3.0.14 on 2022-10-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title_en', models.CharField(db_tablespace='', max_length=100, verbose_name='Title (English)')),
                ('title_ru', models.CharField(blank=True, db_tablespace='', max_length=100, verbose_name='Title (Russian)')),
                ('title_fr', models.CharField(blank=True, db_tablespace='', max_length=100, verbose_name='Title (French)')),
                ('title_de', models.CharField(blank=True, db_tablespace='', max_length=100, verbose_name='Title (German)')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
