# Generated by Django 3.0.14 on 2022-10-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='Title', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CategoryTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=7, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category Translations',
                'verbose_name_plural': 'Category Translations',
                'ordering': ['language'],
                'unique_together': {('category', 'language')},
            },
        ),
    ]
